### ISSUE TITLE
Prevent SQL results to be logged to the console

### ISSUE THREAD

**Issue by pberden** [gantrim/node-teradata#5]
Hi, first thanks for publishing this node package. Great work!
I'm using it like so:

```
app.get('/api/v1/select', function (req, res) {
  teradata.connect('jdbc:teradata://server' ,'user', 'pass')
    .then(function () {       
      return teradata.executeQuery("SELECT * FROM ...", 1000);
    })
    .then(function (results) {
      res.write(JSON.stringify({"data": results}));
      res.end();
      })
    .then(function () {
      return teradata.disconnect();
    });
});
```

The results of the SQL statement are logged to the console. Is there a way to disable this?

**Comment by gantrim** [comment]
Glad people are finding it useful. I have not been able to develop this as actively as I'd like but my eventual goal was to add something like a verbose option so you could enable/disable this. I'm also open to suggestions. It should be trivial. You are welcome to submit a PR if you like, otherwise I will add it within the next couple days here.

If you need it now, you can fork this package and install via git url. The only change you should need to make is in [Teradata.js](https://github.com/gantrim/node-teradata/blob/release-0.0.n/lib/Teradata.js) simply remove the console.log statement on line 81.

**Comment by pberden** [comment]
Hi Greg, I did not realize the package had such a small codebase. I have forked your repository and will see if I can add such a verbose option. If you can direct me to an example node module where I can see what a proper way of adding config options to a node module, that would be great.

**Comment by ubershmekel** [comment]
Yes. Thank you for this library. I would recommend disabling the `console.log` until the `verbose` feature lands.

**Comment by gantrim** [comment]
I have merged your pull request. Logging will be disabled until a verbose option is implemented. Thanks for your effort.

**Comment by gantrim** [comment]
just wanted to let everyone here know that i have implemented verbose and logging is turned off by default now. See the updated readme for details.
